compatibility_date = "2024-05-12"

# Cloudflare D1 Database binding for Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "budget-tracker-db"
database_id = "1efbe4a4-1848-4325-bbc8-12d3cf3f06ac"
migrations_dir = "db/migrations"
