-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  color TEXT NOT NULL,
  type TEXT CHECK(type IN ('income', 'expense')) NOT NULL,
  group_name TEXT NOT NULL,
  is_default INTEGER DEFAULT 0, -- 1 for system categories, 0 for user created
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,
  amount REAL NOT NULL,
  type TEXT CHECK(type IN ('income', 'expense')) NOT NULL,
  category_id TEXT NOT NULL,
  date TEXT NOT NULL, -- YYYY-MM-DD format
  description TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(category_id) REFERENCES categories(id)
);

-- Insert Default Categories (Seeded System Categories, is_default = 1)
DELETE FROM transactions;
DELETE FROM categories;

INSERT INTO categories (id, name, icon, color, type, group_name, is_default) VALUES
('c-food-drinks-delivery', 'Delivery', 'local_shipping', '#ff9100', 'expense', 'food_drinks', 1),
('c-food-drinks-restaurant', 'Restaurant', 'restaurant', '#ff9100', 'expense', 'food_drinks', 1),
('c-food-drinks-groceries', 'Groceries', 'local_grocery_store', '#ff9100', 'expense', 'food_drinks', 1),
('c-shopping-drug-store-chemist', 'Drug-store, chemist', 'local_pharmacy', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-leisure-time', 'Leisure time', 'sports_esports', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-stationery-tools', 'Stationery, tools', 'construction', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-gifts-joy', 'Gifts, joy', 'card_giftcard', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-electronics-accessories', 'Electronics, accessories', 'devices', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-pets-animals', 'Pets, animals', 'pets', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-home-garden', 'Home, garden', 'yard', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-flowers', 'Flowers', 'local_florist', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-health-beauty', 'Health and beauty', 'spa', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-jewels-accessories', 'Jewels, accessories', 'diamond', '#8e44ad', 'expense', 'shopping', 1),
('c-shopping-clothes-footwear', 'Clothes & Footwear', 'checkroom', '#8e44ad', 'expense', 'shopping', 1),
('c-housing-property-insurance', 'Property insurance', 'shield', '#2979ff', 'expense', 'housing', 1),
('c-housing-maintenance-repairs', 'Maintenance, repairs', 'handyman', '#2979ff', 'expense', 'housing', 1),
('c-housing-services', 'Services', 'room_service', '#2979ff', 'expense', 'housing', 1),
('c-housing-energy-utilities', 'Energy, utilities', 'electric_bolt', '#2979ff', 'expense', 'housing', 1),
('c-housing-mortgage', 'Mortgage', 'account_balance', '#2979ff', 'expense', 'housing', 1),
('c-housing-rent', 'Rent', 'home', '#2979ff', 'expense', 'housing', 1),
('c-transportation-business-trips', 'Business trips', 'business_center', '#0288d1', 'expense', 'transportation', 1),
('c-transportation-long-distance', 'Long distance', 'commute', '#0288d1', 'expense', 'transportation', 1),
('c-transportation-taxi', 'Taxi', 'local_taxi', '#0288d1', 'expense', 'transportation', 1),
('c-transportation-public-transport', 'Public transport', 'directions_bus', '#0288d1', 'expense', 'transportation', 1),
('c-vehicle-leasing', 'Leasing', 'request_quote', '#455a64', 'expense', 'vehicle', 1),
('c-vehicle-insurance', 'Vehicle insurance', 'verified_user', '#455a64', 'expense', 'vehicle', 1),
('c-vehicle-rentals', 'Rentals', 'car_rental', '#455a64', 'expense', 'vehicle', 1),
('c-vehicle-maintenance', 'Vehicle maintenance', 'build', '#455a64', 'expense', 'vehicle', 1),
('c-vehicle-parking', 'Parking', 'local_parking', '#455a64', 'expense', 'vehicle', 1),
('c-vehicle-fuel', 'Fuel', 'local_gas_station', '#455a64', 'expense', 'vehicle', 1),
('c-life-entertainment-lottery-gambling', 'Lottery, gambling', 'casino', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-alcohol-tobacco', 'Alcohol, tobacco', 'liquor', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-charity-gifts', 'Charity, gifts', 'volunteer_activism', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-holiday-trips-hotels', 'Holiday, trips, hotels', 'flight_takeoff', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-tv-streaming', 'TV, Streaming', 'live_tv', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-books-audio-subscriptions', 'Books, audio, subscriptions', 'library_books', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-education-development', 'Education, development', 'school', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-hobbies', 'Hobbies', 'palette', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-life-events', 'Life events', 'celebration', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-culture-sport-events', 'Culture, sport events', 'emoji_events', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-active-sport-fitness', 'Active sport, fitness', 'fitness_center', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-wellness-beauty', 'Wellness, beauty', 'face', '#ff1744', 'expense', 'life_entertainment', 1),
('c-life-entertainment-health-care-doctor', 'Health care, doctor', 'medical_services', '#ff1744', 'expense', 'life_entertainment', 1),
('c-communication-pc-postal-services', 'Postal services', 'local_post_office', '#00acc1', 'expense', 'communication_pc', 1),
('c-communication-pc-software-apps-games', 'Software, apps, games', 'sports_esports', '#00acc1', 'expense', 'communication_pc', 1),
('c-communication-pc-internet', 'Internet', 'language', '#00acc1', 'expense', 'communication_pc', 1),
('c-communication-pc-telephony-mobile-phone', 'Telephony, mobile phone', 'phone_iphone', '#00acc1', 'expense', 'communication_pc', 1),
('c-financial-expenses-child-support', 'Child Support', 'family_restroom', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-charges-fees', 'Charges, Fees', 'payments', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-advisory', 'Advisory', 'support_agent', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-fines', 'Fines', 'gavel', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-loans-interests', 'Loans, interests', 'account_balance', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-insurances', 'Insurances', 'shield', '#607d8b', 'expense', 'financial_expenses', 1),
('c-financial-expenses-taxes', 'Taxes', 'receipt_long', '#607d8b', 'expense', 'financial_expenses', 1),
('c-investments-collections', 'Collections', 'collections_bookmark', '#2e7d32', 'expense', 'investments', 1),
('c-investments-savings', 'Savings', 'savings', '#2e7d32', 'expense', 'investments', 1),
('c-investments-financial-investments', 'Financial investments', 'trending_up', '#2e7d32', 'expense', 'investments', 1),
('c-investments-vehicles-chattels', 'Vehicles, chattels', 'directions_car', '#2e7d32', 'expense', 'investments', 1),
('c-investments-realty', 'Realty', 'real_estate_agent', '#2e7d32', 'expense', 'investments', 1),
('c-income-gifts', 'Gifts', 'redeem', '#00a878', 'income', 'income', 1),
('c-income-child-support', 'Child Support', 'family_restroom', '#00a878', 'income', 'income', 1),
('c-income-refunds-tax-purchase', 'Refunds (tax, purchase)', 'assignment_return', '#00a878', 'income', 'income', 1),
('c-income-lottery-gambling', 'Lottery, gambling', 'casino', '#00a878', 'income', 'income', 1),
('c-income-checks-coupons', 'Checks, coupons', 'confirmation_number', '#00a878', 'income', 'income', 1),
('c-income-lending-renting', 'Lending, renting', 'handshake', '#00a878', 'income', 'income', 1),
('c-income-dues-grants', 'Dues & grants', 'account_balance_wallet', '#00a878', 'income', 'income', 1),
('c-income-rental-income', 'Rental income', 'apartment', '#00a878', 'income', 'income', 1),
('c-income-sale', 'Sale', 'sell', '#00a878', 'income', 'income', 1),
('c-income-interests-dividends', 'Interests, dividends', 'show_chart', '#00a878', 'income', 'income', 1),
('c-income-wage-invoices', 'Wage, invoices', 'payments', '#00a878', 'income', 'income', 1),
('c-others-missing', 'Missing', 'help', '#78909c', 'expense', 'others', 1);
